### ISSUE TITLE
Về việc chuẩn hóa dấu câu

### ISSUE THREAD

**Issue by rain1024** [langmaninternet/VietnameseTextNormalizer#1]
Anh cho em hỏi một chút về việc chuẩn hóa dấu câu ạ.

Ở file README anh có Việt 

```
Thư viện chuẩn hóa text Tiếng Việt cho python, có 1 số tính năng sau :

Chuẩn hóa dấu về kiểu phổ thông. Ví dụ : [hoà] -> [hòa]
```

Anh cho em hỏi **kiểu phổ thông** là kiểu gì ạ? Có tài liệu mô tả về cách bỏ dấu theo **kiểu phổ thông** không ạ?

Em xin cảm ơn :D

**Comment by xengvn** [comment]
Dear bạn Vu Anh

Trong tiếng việt có 2 kiểu đặt dấu tiếng việt chính 

https://vi.wikipedia.org/wiki/Quy_t%E1%BA%AFc_%C4%91%E1%BA%B7t_d%E1%BA%A5u_thanh_trong_ch%E1%BB%AF_qu%E1%BB%91c_ng%E1%BB%AF#Ki%E1%BB%83u_c%C5%A9


Theo dữ liệu thống kê 3M bài báo từ các nguồn báo điện tử thì mình thấy [kiểu cũ] (gọi theo wiki) được nhiều hơn hẳn, nên mình gọi là nó [kiểu phổ thông] (thông dụng và được dùng nhiều)

Cám ơn bạn

**Comment by rain1024** [comment]
Vâng, em cảm ơn anh ạ
