### ISSUE TITLE
module 'VietnameseTextNormalizer' has no attribute 'Normalize'

### ISSUE THREAD

**Issue by win95** [langmaninternet/VietnameseTextNormalizer#10]
<ipython-input-200-f5298cf9b562> in <module>
      1 import VietnameseTextNormalizer
----> 2 a=VietnameseTextNormalizer.Normalize(u"UCS2 : Tôi làm việ ở ban công ngệ FPT, tôi là người viêt nam. hôm nay tôi ko thích ăn mì tôm. tôi làm đc 2 bài tập.");
      3 print (a)

AttributeError: module 'VietnameseTextNormalizer' has no attribute 'Normalize'

**Comment by langmaninternet** [comment]
bạn có thể nói rõ thêm môi trường test của bạn và version python của bạn được ko ?

chỉ mỗi như này thì mình cũng ko biết là lỗi ntn

**Comment by win95** [comment]
Enviroment:
- jupyter-notebook version last
- version python3.6

**Comment by langmaninternet** [comment]
bạn chạy câu lệnh sau để biết thư mục đang chạy
>>import os
>>print os.getcwd()
Sau đó bạn cần bảo đảm rằng file VietnameseTextNormalizer.so tương ứng có ở trong thư mục đó nhé
