### ISSUE TITLE
Lỗi khi build

### ISSUE THREAD

**Issue by lufutu** [langmaninternet/VietnameseTextNormalizer#12]
Hi anh,
Em có thử build trên Ubuntu 18.04 thì bị lỗi 
`Makefile:19: recipe for target 'ObjectPython3/VietnameseTextNormalizer.o' failed
make: *** [ObjectPython3/VietnameseTextNormalizer.o] Interrupt`
Em đang cài python3-dev và  g++, Ubuntu 18.0.4
Em đọc các issues khác thấy nhiều người bị lỗi này cả MacOs.
Thanks anh.

**Comment by langmaninternet** [comment]
Dear bạn,

Bạn để ý xem python3-dev của bạn là version bao nhiêu, đường gẫn /usr/include/python3.6 có tồn tại hay ko

Ngoài ra bạn có thể cho mình chi tiết thêm thông tin ko, vì mình vừa clone về build thử vẫn ok:

**Comment by lufutu** [comment]
Em đã build được khi clone bản mới hôm nay.
Thanks anh.
