### ISSUE TITLE
Makefile python3

### ISSUE THREAD

**Issue by annhienht** [langmaninternet/VietnameseTextNormalizer#14]
Chào các anh, em mới tập tành mong các anh giúp em với. Em bị gặp ngay vấn đề khi makefile
  
<img width="794" alt="image" src="https://user-images.githubusercontent.com/82326998/115269856-eb840a00-a165-11eb-9140-b5a77286cb1d.png">

**Comment by langmaninternet** [comment]
hi bạn,
bạn cần cài python dev và setup path đến thư mục include của python dev như trong hướng dẫn
