### ISSUE TITLE
bạn chưa setup giá trị cho biến môi trường GPP_COMPILER  nhé bạn

### ISSUE THREAD

**Issue by tvlanh** [langmaninternet/VietnameseTextNormalizer#17]
Mình dùng chip M1,ko biết fix được lỗi này ko bạn,mình đã cài python3.9 vẫn báo như bên dưới ạ!
ld: library not found for -lpython3.10
collect2: error: ld returned 1 exit status

$GPP_COMPILER -shared -o ReleasePython3/VietnameseTextNormalizer.so  ObjectPython3/ContextSystem.o  ObjectPython3/SyllableSystem.o  ObjectPython3/VietnameseTextNormalizer.o  ObjectPython3/WordSystem.o  ObjectPython3/main.o -L. -L$PYTHON3_LIB_PATH -l$PYTHON3_LIB_NAME ; \
        cp -f UnitTestVietnameseTextNormalizer.py ReleasePython3/ ; \
        cd ReleasePython3 ; \
        echo "Build Release Python3 Done" ; \
        echo "Test Python3 - VietnameseTextNormalizer " ; \
        python3 UnitTestVietnameseTextNormalizer.py ; 
ld: library not found for -lpython3.10
collect2: error: ld returned 1 exit status
Build Release Python3 Done
Test Python3 - VietnameseTextNormalizer 
Traceback (most recent call last):
  File "UnitTestVietnameseTextNormalizer.py", line 2, in <module>
    import VietnameseTextNormalizer
ModuleNotFoundError: No module named 'VietnameseTextNormalizer'
make: *** [all] Error 1

**Comment by langmaninternet** [comment]
ld: library not found for -lpython3.10
Bạn cần cấu hình 3 biến  sau đúng với version bạn cài đặt:
PYTHON3_DEV_INCULE 
PYTHON3_LIB_PATH  
PYTHON3_LIB_NAME

ví dụ mẫu trong máy tính của mình:
export PYTHON3_DEV_INCULE=/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/include
export PYTHON3_LIB_PATH=/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib
export PYTHON3_LIB_NAME=python3.9
