### ISSUE TITLE
hướng dẫn cách sử dụng VietnameseTextNormalizer

### ISSUE THREAD

**Issue by TQuy** [langmaninternet/VietnameseTextNormalizer#2]
Anh có thể giải thích cụ thể cách dùng của thử viện này được ko ạ

**Comment by langmaninternet** [comment]
Dear bạn

Mình có file python demo code chạy thử nghiệm đó ạ :
https://github.com/langmaninternet/VietnameseTextNormalizer/blob/master/UnitTestVietnameseTextNormalizer.py

Bước 1 : Mình make ra file thư viện so
Bước 2 : Để file so vào thư mục chạy hoặc thư mục thư viện mặc định
Bước 3 : chạy code giống trong file unit test kia
