### ISSUE TITLE
Bị lỗi khi combine trên macos

### ISSUE THREAD

**Issue by tienthanhdhcn** [langmaninternet/VietnameseTextNormalizer#3]
Cảm ơn Quang đã published một tool rất hữu dụng. Mình có thể deploy và chạy khá ổn trên linux nhưng không thể combine khi dùng macos. Dưới đây là output khi mình chạy `make -j`

`g++  -std=c++17 -shared -o ReleasePython3/VietnameseTextNormalizer.so  ObjectPython3/ContextSystem.o  ObjectPython3/PhonemeSystem.o  ObjectPython3/SyllableSystem.o  ObjectPython3/VietnameseTextNormalizer.o  ObjectPython3/WordSystem.o -L. ; \
        cp -f UnitTestVietnameseTextNormalizer.py ReleasePython3/ ; \
        cd ReleasePython3 ; \
        echo "Build Release Python3 Done" ; \
        echo "Test Python3 - VietnameseTextNormalizer " ; \
        python3 UnitTestVietnameseTextNormalizer.py ; 
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTuple", referenced from:
      VietnameseTextNormalizerStandard(_object*, _object*) in VietnameseTextNormalizer.o
      VietnameseTextNormalizerForASR(_object*, _object*) in VietnameseTextNormalizer.o
      VietnameseTextNormalizerForIToY(_object*, _object*) in VietnameseTextNormalizer.o
  "_PyModule_Create2", referenced from:
      _PyInit_VietnameseTextNormalizer in VietnameseTextNormalizer.o
  "_Py_BuildValue", referenced from:
      VietnameseTextNormalizerStandard(_object*, _object*) in VietnameseTextNormalizer.o
      VietnameseTextNormalizerForASR(_object*, _object*) in VietnameseTextNormalizer.o
      VietnameseTextNormalizerForIToY(_object*, _object*) in VietnameseTextNormalizer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Build Release Python3 Done
Test Python3 - VietnameseTextNormalizer 
Traceback (most recent call last):
  File "UnitTestVietnameseTextNormalizer.py", line 2, in <module>
    import VietnameseTextNormalizer
ModuleNotFoundError: No module named 'VietnameseTextNormalizer'
make: *** [all] Error 1
`

**Comment by langmaninternet** [comment]
Dear anh

Để make được trên MacOS thì mình cần cài gói python3-dev
và sửa lại đường dẫn trong file make ạ -I/usr/include/python3.5

https://stackoverflow.com/questions/41743825/how-to-install-python3-4-dev-for-mac

Hiện tại em chưa có máy MacOS ở đây để thử nghiệm. 
Trong phiên bản sắp tới sẽ có makefile cho MacOS ạ

**Comment by tienthanhdhcn** [comment]
Cảm ơn Quang nhiều, mình có thử nhưng mà vẫn không được. Nên đành phải chạy trên linux server :)
