### ISSUE TITLE
bị lỗi khi cài đặt

### ISSUE THREAD

**Issue by manhcntt21** [langmaninternet/VietnameseTextNormalizer#5]
Bạn ơi, cho mình hỏi với, sao mình cài đặt đủ các thư viện yêu cầu rồi mà sao đến đoạn make -j, vẫn báo lỗi này vậy nhỉ.

g++-5 -std=c++17 -shared -o ReleasePython2/VietnameseTextNormalizer.so  ObjectPython2/VietnameseTextNormalizer.o  ObjectPython2/PhonemeSystem.o  ObjectPython2/SyllableSystem.o  ObjectPython2/ContextSystem.o  ObjectPython2/WordSystem.o -L. ; \
cp -f UnitTestVietnameseTextNormalizer.py ReleasePython2/ ; \
cd ReleasePython2 ; \
echo "Build Release Python2 Done" ; \
echo "Test Python2 - VietnameseTextNormalizer " ; \
python2 UnitTestVietnameseTextNormalizer.py ; \
cd .. ; 	
g++-5: error: ObjectPython2/VietnameseTextNormalizer.o: No such file or directory
g++-5: error: ObjectPython2/PhonemeSystem.o: No such file or directory
g++-5: error: ObjectPython2/SyllableSystem.o: No such file or directory
g++-5: error: ObjectPython2/ContextSystem.o: No such file or directory
g++-5: error: ObjectPython2/WordSystem.o: No such file or directory
g++-5: fatal error: no input files
compilation terminated.
cp: cannot create regular file 'ReleasePython2/': Not a directory
/bin/sh: 3: cd: can't cd to ReleasePython2
Build Release Python2 Done
Test Python2 - VietnameseTextNormalizer 
Traceback (most recent call last):
  File "UnitTestVietnameseTextNormalizer.py", line 2, in <module>
    import VietnameseTextNormalizer
ImportError: No module named VietnameseTextNormalizer

**Comment by langmaninternet** [comment]
Dear bạn
file make file của python 2 bị 1 lỗi nhỏ, mình đã fix rồi ạ
cám ơn bạn đã thông báo
