### ISSUE TITLE
Không thể import VietnameseTextNormalizer

### ISSUE THREAD

**Issue by manhcntt21** [langmaninternet/VietnameseTextNormalizer#7]
Sau khi make -j , kết quả như dưới

$GPP_COMPILER -c -fPIC -O3 -Wall VietnameseTextNormalizer.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/VietnameseTextNormalizer.o  ;
VietnameseTextNormalizer.cpp: In member function ‘void VietnameseTextNormalizer::Normalize()’:
VietnameseTextNormalizer.cpp:4481:15: warning: variable ‘leftTextNodeOffset3’ set but not used [-Wunused-but-set-variable]
    TEXT_NODE* leftTextNodeOffset3 = &nullTextNodeForStep2Normalize;
               ^~~~~~~~~~~~~~~~~~~
VietnameseTextNormalizer.cpp:4507:15: warning: variable ‘rightTextNodeOffset4’ set but not used [-Wunused-but-set-variable]
    TEXT_NODE* rightTextNodeOffset4 = &nullTextNodeForStep2Normalize;
               ^~~~~~~~~~~~~~~~~~~~
$GPP_COMPILER -shared -o ReleasePython3/VietnameseTextNormalizer.so  ObjectPython3/VietnameseTextNormalizer.o  ObjectPython3/PhonemeSystem.o  ObjectPython3/SyllableSystem.o  ObjectPython3/ContextSystem.o  ObjectPython3/WordSystem.o -L. ; \
cp -f UnitTestVietnameseTextNormalizer.py ReleasePython3/ ; \
cd ReleasePython3 ; \
echo "Build Release Python3 Done" ; \
echo "Test Python3 - VietnameseTextNormalizer " ; \
python3 UnitTestVietnameseTextNormalizer.py ; 
Build Release Python3 Done
Test Python3 - VietnameseTextNormalizer 
Init Vietnamese Text Normalizer version 1.0
	Bùi Tấn Quang - langmaninternet@gmail.com
Normalization : 3 change(s) - Utf8 mode
UCS2 : Tôi làm việc ở ban công nghệ FPT, tôi là người viêt nam. hôm nay tôi không thích ăn mì tôm. tôi làm đc 2 bài tập.
Normalization : 3 change(s) - Utf8 mode
 UTF8 : Tôi làm việc ở ban công nghệ FPT, tôi là người viêt nam. hôm nay tôi không thích ăn mì tôm. tôi làm đc 2 bài tập.

Xong sau đó em tạo 1 file python và chạy thử

# -*- coding: utf-8 -*-
import VietnameseTextNormalizer
a=VietnameseTextNormalizer.Normalize(u"UCS2 : Tôi làm việ ở ban công ngệ FPT, tôi là người viêt nam. hôm nay tôi ko thích ăn mì tôm. tôi làm đc 2 bài tập.");
print (a)

thì nó bảo lỗi ko thể import VietnameseTextNormalizer

**Comment by langmaninternet** [comment]
Dear bạn

Khi make xong thì sẽ có 1 file VietnameseTextNormalizer.so ở trong thư mục release

Bạn cần copy file này vào trong thư mục của project thì mới load được

Cám ơn bạn nhiều
