### ISSUE TITLE
Lỗi Core Dump (Segmentation fault)

### ISSUE THREAD

**Issue by cucbui57** [langmaninternet/VietnameseTextNormalizer#8]
Em chào anh,

Em thấy thư viện của anh khá hữu ích và tiền xử lý được khá nhiều dữ liệu.
Hiện tại em đang install trên python 3, và em phát hiện bị lỗi core dump (Segmentation fault) đối với câu: "dùng tiêu bang linh dược". Lỗi này không biết có phải do lib không ạ? 

Em cảm ơn anh.

**Comment by langmaninternet** [comment]
Cám ơn bạn đã phản hồi

Mình đã tìm ra nguyên nhân bug: Để tiết kiệm RAM, mình đã bỏ đi 1 số ô nhớ trong word object nên bị crash khi truy cập đến vùng đó

Mình đã fix hết lỗi này

Cám ơn bạn nhiều
