### ISSUE TITLE
Lỗi khi build với make trên MacOS

### ISSUE THREAD

**Issue by nhatnor123** [langmaninternet/VietnameseTextNormalizer#9]
E chào a ạ.
Issue của e là khi e build trên MacOS theo hướng dẫn của a với python3, đến đoạn "make -j" thì của e bị lỗi như sau : 

$GPP_COMPILER -c -fPIC -O3 -Wall ContextSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/ContextSystem.o  ;
$GPP_COMPILER -c -fPIC -O3 -Wall PhonemeSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/PhonemeSystem.o  ;
$GPP_COMPILER -c -fPIC -O3 -Wall SyllableSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/SyllableSystem.o  ;
$GPP_COMPILER -c -fPIC -O3 -Wall VietnameseTextNormalizer.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/VietnameseTextNormalizer.o  ;
$GPP_COMPILER -c -fPIC -O3 -Wall WordSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/WordSystem.o  ;
/bin/sh: -c: command not found
/bin/sh: -c: command not found
make: *** [ObjectPython3/PhonemeSystem.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [ObjectPython3/ContextSystem.o] Error 127
/bin/sh: -c: command not found
make: *** [ObjectPython3/SyllableSystem.o] Error 127
/bin/sh: -c: command not found
make: *** [ObjectPython3/VietnameseTextNormalizer.o] Error 127
/bin/sh: -c: command not found
make: *** [ObjectPython3/WordSystem.o] Error 127

Mong a có thể chỉ e cách giải quyết ạ. 
E cảm ơn a.

**Comment by cuongnm71** [comment]
> E chào a ạ.
> Issue của e là khi e build trên MacOS theo hướng dẫn của a với python3, đến đoạn "make -j" thì của e bị lỗi như sau :
> 
> $GPP_COMPILER -c -fPIC -O3 -Wall ContextSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/ContextSystem.o ;
> $GPP_COMPILER -c -fPIC -O3 -Wall PhonemeSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/PhonemeSystem.o ;
> $GPP_COMPILER -c -fPIC -O3 -Wall SyllableSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/SyllableSystem.o ;
> $GPP_COMPILER -c -fPIC -O3 -Wall VietnameseTextNormalizer.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/VietnameseTextNormalizer.o ;
> $GPP_COMPILER -c -fPIC -O3 -Wall WordSystem.cpp -I$PYTHON3_DEV_INCULE -o ObjectPython3/WordSystem.o ;
> /bin/sh: -c: command not found
> /bin/sh: -c: command not found
> make: *** [ObjectPython3/PhonemeSystem.o] Error 127
> make: *** Waiting for unfinished jobs....
> make: *** [ObjectPython3/ContextSystem.o] Error 127
> /bin/sh: -c: command not found
> make: *** [ObjectPython3/SyllableSystem.o] Error 127
> /bin/sh: -c: command not found
> make: *** [ObjectPython3/VietnameseTextNormalizer.o] Error 127
> /bin/sh: -c: command not found
> make: *** [ObjectPython3/WordSystem.o] Error 127
> 
> Mong a có thể chỉ e cách giải quyết ạ.
> E cảm ơn a.

mình bị lỗi y hệt vậy, k biết bạn fix đc chưa?

**Comment by langmaninternet** [comment]
Dear bạn

bạn cần setup 2 biến môi trường sau rồi mới chạy câu lệnh make được

export PYTHON2_DEV_INCULE=/usr/include/python2.7
export GPP_COMPILER=g++

hoặc
export PYTHON3_DEV_INCULE=/usr/include/python2.7
export GPP_COMPILER=g++


PYTHON2_DEV_INCULE : thư mục chứa python dev của bạn
GPP_COMPILER là g++ mà bạn đang có
